version: '2.29.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: gunicorn --bind 0.0.0.0:8000 rateme.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/frontend